version: '3'
services:
    nginx:
        image: nginx:1.21
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/usr/share/nginx/html:cached
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/ssl:/etc/nginx/ssl
        depends_on:
            - php
        links:
            - php

    php:
        image: php:8.1-fpm
        environment:
            - APP_ENVIRONMENT=${APP_ENVIRONMENT}
        volumes:
            - ./:/usr/share/nginx/html:cached
        depends_on:
            - sql
            - redis
        links:
            - sql
            - redis

    sql:
        image: mysql/mysql-server:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_USER=${DB_USER_NAME}
            - MYSQL_PASSWORD=${DB_USER_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
        ports:
            - "3306:3306"
        volumes:
            - sqldata:/var/lib/mysql

    redis:
        image: redis:6.2
        volumes:
            - redisdata:/data

volumes:
    sqldata:
    redisdata: